### ISSUE TITLE
(SOAP-ENV:Client) 20110 - Input error

### ISSUE THREAD

**Issue by elmo** [davidsantoso/markety#33] opened 2015-07-15 22:52 UTC
Hello,

I've been using your excellent library to integrate with Marketo.  I'd been cruising along until I hit a wall trying to add a custom object.

From the doc:

custom_object = Markety::CustomObject.new(
    object_type_name: "Roadshow",
    keys: {"MKTOID" => 1090177, "rid" => "rid1"},
    attributes: {"city" => "SanMateo", "zip" => 94404 })

Is MKTOID the lead.idnum?

Here's the specific call I'm using:

```
 marketo_child = Markety::CustomObject.new(
   object_type_name: "Child",
   keys: {"MKTOID" => lead.idnum, "child_id" => "child1"},
   attributes: {
     "first_name" => "Little",
     "last_name" => "Elmo",
     "interest1" => "chess",
     "interest2" => "tennis",
     "interest3" => "skiing",
     "interest4" => "sleeping",
     "interest5" => "cooking"
   }
 )
```

Here's the response I'm getting:

 #<Markety::Response::SyncCustomObjectResponse:0x007f9a08a026f8 @response=#<Savon::SOAPFault: (SOAP-ENV:Client) 20110 - Input error>, @success=false, @error_message="(SOAP-ENV:Client) 20110 - Input error">

**Comment by davidsantoso** [comment] 2015-07-16 13:43
Hey @elmo thanks for submitting the issue. I'm a bit busy today so I might not be able to look at it until tomorrow, but I will take a look! Also, unfortunately I no longer have access to a Marketo instance so I can't actually verify changes. If you're up for it, you're welcome to submit a PR if you know what the issue is, but best bet is that if I do find the issue, I'll need you to test it out.

**Comment by davidsantoso** [comment] 2015-07-18 14:12
@elmo, so looking at it closer, I'm realizing that I think `MKTOID` is actually a attribute you specify on a `customObject`. Which I imagine is defined within your Marketo instance. The README uses it as an example but I don't think it's a required attribute, if that makes sense. `Input error` could be because Marketo couldn't find the `MKTOID` field?

Let me know. I could've misread the docs!

**Comment by davidsantoso** [comment] 2015-07-21 16:21
@elmo, I'm closing this issue for now. Let me know if it's not a matter of a custom field not being available in your Marketo instance.

**Closed as completed by davidsantoso** 2015-07-21 16:21 UTC

**Comment by elmo** [comment] 2015-07-21 16:30
You're right.  Marketo said that custom objects were enabled, but they were not.  They are now, and everything is fine.  Thanks for looking into it.
